language: julia
os:
  - linux
julia:
  - 0.5
notifications:
  email: false
script:		
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi		
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("QMDP"); Pkg.test("QMDP"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("QMDP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
